-- ============================================================================
-- SIMP - Views para Dashboard e IA (Versão 2.0)
-- Com Score de Saúde e Classificação de Problemas
-- ============================================================================

-- ============================================================================
-- VIEW 1: VW_DASHBOARD_RESUMO_GERAL
-- Cards principais do dashboard
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_DASHBOARD_RESUMO_GERAL')
    DROP VIEW [dbo].[VW_DASHBOARD_RESUMO_GERAL];
GO

CREATE VIEW [dbo].[VW_DASHBOARD_RESUMO_GERAL]
AS
SELECT 
    -- Totais
    COUNT(DISTINCT CD_PONTO_MEDICAO) AS TOTAL_PONTOS,
    SUM(QTD_REGISTROS) AS TOTAL_MEDICOES,
    
    -- Score de Saúde
    CAST(AVG(CAST(VL_SCORE_SAUDE AS DECIMAL(5,2))) AS DECIMAL(5,2)) AS SCORE_MEDIO,
    MIN(VL_SCORE_SAUDE) AS SCORE_MINIMO,
    SUM(CASE WHEN VL_SCORE_SAUDE >= 8 THEN 1 ELSE 0 END) AS PONTOS_SAUDAVEIS,
    SUM(CASE WHEN VL_SCORE_SAUDE BETWEEN 5 AND 7 THEN 1 ELSE 0 END) AS PONTOS_ALERTA,
    SUM(CASE WHEN VL_SCORE_SAUDE < 5 THEN 1 ELSE 0 END) AS PONTOS_CRITICOS,
    
    -- Por tipo de problema
    SUM(CASE WHEN DS_TIPO_PROBLEMA = 'COMUNICACAO' THEN 1 ELSE 0 END) AS PROBLEMAS_COMUNICACAO,
    SUM(CASE WHEN DS_TIPO_PROBLEMA = 'MEDIDOR' THEN 1 ELSE 0 END) AS PROBLEMAS_MEDIDOR,
    SUM(CASE WHEN DS_TIPO_PROBLEMA = 'HIDRAULICO' THEN 1 ELSE 0 END) AS PROBLEMAS_HIDRAULICO,
    SUM(CASE WHEN DS_TIPO_PROBLEMA = 'VERIFICAR' THEN 1 ELSE 0 END) AS PROBLEMAS_VERIFICAR,
    
    -- Anomalias
    SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) AS TOTAL_ANOMALIAS,
    CAST(SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0) AS DECIMAL(5,2)) AS PERC_ANOMALIA,
    
    -- Tratamentos
    SUM(CASE WHEN ID_SITUACAO = 2 THEN 1 ELSE 0 END) AS PONTOS_TRATADOS,
    SUM(QTD_TRATAMENTOS) AS TOTAL_TRATAMENTOS,
    
    -- Completude
    SUM(CASE WHEN QTD_REGISTROS >= 1400 THEN 1 ELSE 0 END) AS PONTOS_COMPLETOS,
    CAST(AVG(QTD_REGISTROS * 100.0 / 1440) AS DECIMAL(5,2)) AS COMPLETUDE_MEDIA,
    
    -- Período
    MIN(DT_MEDICAO) AS DATA_INICIO,
    MAX(DT_MEDICAO) AS DATA_FIM

FROM [dbo].[MEDICAO_RESUMO_DIARIO]
WHERE DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE));
GO

-- ============================================================================
-- VIEW 2: VW_PONTOS_POR_SCORE_SAUDE
-- Ranking de pontos ordenados por score de saúde
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_PONTOS_POR_SCORE_SAUDE')
    DROP VIEW [dbo].[VW_PONTOS_POR_SCORE_SAUDE];
GO

CREATE VIEW [dbo].[VW_PONTOS_POR_SCORE_SAUDE]
AS
SELECT 
    MRD.CD_PONTO_MEDICAO,
    PM.DS_NOME AS NOME_PONTO,
    PM.CD_PONTO_MEDICAO_ID AS CODIGO_PONTO,
    MRD.ID_TIPO_MEDIDOR,
    CASE MRD.ID_TIPO_MEDIDOR
        WHEN 1 THEN 'M - Macromedidor'
        WHEN 2 THEN 'E - Estação Pitométrica'
        WHEN 4 THEN 'P - Pressão'
        WHEN 6 THEN 'R - Nível Reservatório'
        WHEN 8 THEN 'H - Hidrômetro'
    END AS TIPO_MEDIDOR,
    
    -- Score de saúde
    AVG(MRD.VL_SCORE_SAUDE) AS SCORE_MEDIO,
    MIN(MRD.VL_SCORE_SAUDE) AS SCORE_MINIMO,
    
    -- Classificação visual
    CASE 
        WHEN AVG(MRD.VL_SCORE_SAUDE) >= 8 THEN 'SAUDAVEL'
        WHEN AVG(MRD.VL_SCORE_SAUDE) >= 5 THEN 'ALERTA'
        ELSE 'CRITICO'
    END AS STATUS_SAUDE,
    
    -- Cor para dashboard
    CASE 
        WHEN AVG(MRD.VL_SCORE_SAUDE) >= 8 THEN '#22c55e'  -- Verde
        WHEN AVG(MRD.VL_SCORE_SAUDE) >= 5 THEN '#f59e0b'  -- Amarelo
        ELSE '#dc2626'  -- Vermelho
    END AS COR_STATUS,
    
    -- Ícone
    CASE 
        WHEN AVG(MRD.VL_SCORE_SAUDE) >= 8 THEN 'checkmark-circle'
        WHEN AVG(MRD.VL_SCORE_SAUDE) >= 5 THEN 'warning'
        ELSE 'alert-circle'
    END AS ICONE_STATUS,
    
    -- Contagens de problemas
    COUNT(*) AS DIAS_ANALISADOS,
    SUM(CASE WHEN MRD.FL_SEM_COMUNICACAO = 1 THEN 1 ELSE 0 END) AS DIAS_SEM_COMUNICACAO,
    SUM(CASE WHEN MRD.FL_VALOR_CONSTANTE = 1 THEN 1 ELSE 0 END) AS DIAS_VALOR_CONSTANTE,
    SUM(CASE WHEN MRD.FL_VALOR_NEGATIVO = 1 THEN 1 ELSE 0 END) AS DIAS_VALOR_NEGATIVO,
    SUM(CASE WHEN MRD.FL_FORA_FAIXA = 1 THEN 1 ELSE 0 END) AS DIAS_FORA_FAIXA,
    SUM(CASE WHEN MRD.FL_SPIKE = 1 THEN 1 ELSE 0 END) AS DIAS_COM_SPIKE,
    SUM(CASE WHEN MRD.FL_ZEROS_SUSPEITOS = 1 THEN 1 ELSE 0 END) AS DIAS_ZEROS_SUSPEITOS,
    
    -- Problema mais frequente
    (SELECT TOP 1 DS_TIPO_PROBLEMA 
     FROM [dbo].[MEDICAO_RESUMO_DIARIO] MRD2
     WHERE MRD2.CD_PONTO_MEDICAO = MRD.CD_PONTO_MEDICAO
       AND MRD2.DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
       AND MRD2.DS_TIPO_PROBLEMA IS NOT NULL
     GROUP BY DS_TIPO_PROBLEMA
     ORDER BY COUNT(*) DESC) AS PROBLEMA_PRINCIPAL,
    
    -- Estatísticas
    AVG(MRD.VL_MEDIA_DIARIA) AS MEDIA_PERIODO,
    AVG(MRD.QTD_REGISTROS) AS REGISTROS_MEDIO,
    AVG(MRD.VL_DESVIO_HISTORICO) AS DESVIO_HISTORICO_MEDIO

FROM [dbo].[MEDICAO_RESUMO_DIARIO] MRD
LEFT JOIN [dbo].[PONTO_MEDICAO] PM ON MRD.CD_PONTO_MEDICAO = PM.CD_PONTO_MEDICAO
WHERE MRD.DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
GROUP BY 
    MRD.CD_PONTO_MEDICAO, PM.DS_NOME, PM.CD_PONTO_MEDICAO_ID, MRD.ID_TIPO_MEDIDOR;
GO

-- ============================================================================
-- VIEW 3: VW_PROBLEMAS_COMUNICACAO
-- Pontos com problemas de telemetria/comunicação
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_PROBLEMAS_COMUNICACAO')
    DROP VIEW [dbo].[VW_PROBLEMAS_COMUNICACAO];
GO

CREATE VIEW [dbo].[VW_PROBLEMAS_COMUNICACAO]
AS
SELECT 
    MRD.CD_PONTO_MEDICAO,
    PM.DS_NOME AS NOME_PONTO,
    MRD.DT_MEDICAO,
    MRD.QTD_REGISTROS,
    MRD.QTD_HORAS_SEM_DADO,
    CAST(MRD.QTD_REGISTROS * 100.0 / 1440 AS DECIMAL(5,2)) AS PERC_COMPLETUDE,
    
    -- Tipo específico
    CASE 
        WHEN MRD.FL_SEM_COMUNICACAO = 1 THEN 'SEM_COMUNICACAO'
        WHEN MRD.FL_VALOR_CONSTANTE = 1 THEN 'VALOR_TRAVADO'
        WHEN MRD.FL_ZEROS_SUSPEITOS = 1 THEN 'ZEROS_SUSPEITOS'
    END AS TIPO_PROBLEMA,
    
    -- Descrição
    CASE 
        WHEN MRD.FL_SEM_COMUNICACAO = 1 THEN 'Menos de 50% dos registros esperados - possível falha de rádio/bateria/datalogger'
        WHEN MRD.FL_VALOR_CONSTANTE = 1 THEN 'Valor constante por muito tempo - possível sensor travado'
        WHEN MRD.FL_ZEROS_SUSPEITOS = 1 THEN 'Zeros quando histórico indica valores - verificar obstrução ou falha'
    END AS DS_DIAGNOSTICO,
    
    MRD.QTD_VALORES_DISTINTOS,
    MRD.VL_SCORE_SAUDE

FROM [dbo].[MEDICAO_RESUMO_DIARIO] MRD
LEFT JOIN [dbo].[PONTO_MEDICAO] PM ON MRD.CD_PONTO_MEDICAO = PM.CD_PONTO_MEDICAO
WHERE MRD.DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
  AND MRD.DS_TIPO_PROBLEMA = 'COMUNICACAO';
GO

-- ============================================================================
-- VIEW 4: VW_PROBLEMAS_MEDIDOR
-- Pontos com problemas no medidor físico
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_PROBLEMAS_MEDIDOR')
    DROP VIEW [dbo].[VW_PROBLEMAS_MEDIDOR];
GO

CREATE VIEW [dbo].[VW_PROBLEMAS_MEDIDOR]
AS
SELECT 
    MRD.CD_PONTO_MEDICAO,
    PM.DS_NOME AS NOME_PONTO,
    MRD.DT_MEDICAO,
    MRD.ID_TIPO_MEDIDOR,
    
    -- Flags específicas
    MRD.FL_VALOR_CONSTANTE,
    MRD.FL_PERFIL_ANOMALO,
    MRD.QTD_VALORES_DISTINTOS,
    MRD.VL_DESVIO_PADRAO,
    
    -- Diagnóstico
    CASE 
        WHEN MRD.FL_VALOR_CONSTANTE = 1 AND MRD.FL_PERFIL_ANOMALO = 1 
        THEN 'Sensor travado - valor constante sem variação natural'
        WHEN MRD.FL_VALOR_CONSTANTE = 1 
        THEN 'Possível travamento do sensor ou conversor A/D'
        WHEN MRD.FL_PERFIL_ANOMALO = 1 
        THEN 'Perfil diário anormal - linha reta sem padrão típico'
    END AS DS_DIAGNOSTICO,
    
    -- Comparação com histórico
    MRD.VL_MEDIA_DIARIA,
    MRD.VL_MEDIA_HISTORICA,
    MRD.VL_DESVIO_HISTORICO,
    MRD.VL_SCORE_SAUDE,
    MRD.DS_ANOMALIAS

FROM [dbo].[MEDICAO_RESUMO_DIARIO] MRD
LEFT JOIN [dbo].[PONTO_MEDICAO] PM ON MRD.CD_PONTO_MEDICAO = PM.CD_PONTO_MEDICAO
WHERE MRD.DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
  AND MRD.DS_TIPO_PROBLEMA = 'MEDIDOR';
GO

-- ============================================================================
-- VIEW 5: VW_PROBLEMAS_HIDRAULICOS
-- Pontos com problemas de validação hidráulica
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_PROBLEMAS_HIDRAULICOS')
    DROP VIEW [dbo].[VW_PROBLEMAS_HIDRAULICOS];
GO

CREATE VIEW [dbo].[VW_PROBLEMAS_HIDRAULICOS]
AS
SELECT 
    MRD.CD_PONTO_MEDICAO,
    PM.DS_NOME AS NOME_PONTO,
    MRD.DT_MEDICAO,
    MRD.ID_TIPO_MEDIDOR,
    
    -- Valores e limites
    MRD.VL_MEDIA_DIARIA,
    MRD.VL_MIN_DIARIO,
    MRD.VL_MAX_DIARIO,
    MRD.VL_LIMITE_INFERIOR,
    MRD.VL_LIMITE_SUPERIOR,
    MRD.VL_CAPACIDADE_NOMINAL,
    
    -- Flags
    MRD.FL_VALOR_NEGATIVO,
    MRD.FL_FORA_FAIXA,
    MRD.FL_SPIKE,
    MRD.QTD_NEGATIVOS,
    MRD.QTD_FORA_FAIXA,
    MRD.QTD_SPIKES,
    
    -- Diagnóstico detalhado
    CASE 
        WHEN MRD.FL_VALOR_NEGATIVO = 1 
        THEN 'VALOR NEGATIVO: ' + CAST(MRD.VL_MIN_DIARIO AS VARCHAR) + ' - Erro de escala ou problema no sensor'
        WHEN MRD.FL_FORA_FAIXA = 1 AND MRD.VL_MAX_DIARIO > ISNULL(MRD.VL_LIMITE_SUPERIOR, MRD.VL_CAPACIDADE_NOMINAL)
        THEN 'ACIMA DO LIMITE: Máx=' + CAST(CAST(MRD.VL_MAX_DIARIO AS DECIMAL(10,2)) AS VARCHAR) + 
             ' > Limite=' + CAST(CAST(ISNULL(MRD.VL_LIMITE_SUPERIOR, MRD.VL_CAPACIDADE_NOMINAL) AS DECIMAL(10,2)) AS VARCHAR)
        WHEN MRD.FL_FORA_FAIXA = 1 
        THEN 'ABAIXO DO LIMITE: Mín=' + CAST(CAST(MRD.VL_MIN_DIARIO AS DECIMAL(10,2)) AS VARCHAR)
        WHEN MRD.FL_SPIKE = 1 
        THEN 'SPIKES DETECTADOS: ' + CAST(MRD.QTD_SPIKES AS VARCHAR) + ' horas com variação > 200%'
    END AS DS_DIAGNOSTICO,
    
    MRD.VL_SCORE_SAUDE,
    MRD.DS_ANOMALIAS

FROM [dbo].[MEDICAO_RESUMO_DIARIO] MRD
LEFT JOIN [dbo].[PONTO_MEDICAO] PM ON MRD.CD_PONTO_MEDICAO = PM.CD_PONTO_MEDICAO
WHERE MRD.DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
  AND MRD.DS_TIPO_PROBLEMA = 'HIDRAULICO';
GO

-- ============================================================================
-- VIEW 6: VW_DISTRIBUICAO_ANOMALIAS
-- Estatísticas de tipos de anomalias
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_DISTRIBUICAO_ANOMALIAS')
    DROP VIEW [dbo].[VW_DISTRIBUICAO_ANOMALIAS];
GO

CREATE VIEW [dbo].[VW_DISTRIBUICAO_ANOMALIAS]
AS
SELECT 
    TRIM(value) AS TIPO_ANOMALIA,
    COUNT(*) AS OCORRENCIAS,
    COUNT(DISTINCT CD_PONTO_MEDICAO) AS PONTOS_AFETADOS,
    
    -- Categorização
    CASE 
        WHEN TRIM(value) LIKE '%COMUNICACAO%' OR TRIM(value) LIKE '%INCOMPLETO%' THEN 'COMUNICACAO'
        WHEN TRIM(value) LIKE '%CONSTANTE%' OR TRIM(value) LIKE '%PERFIL%' THEN 'MEDIDOR'
        WHEN TRIM(value) LIKE '%NEGATIVO%' OR TRIM(value) LIKE '%LIMITE%' OR TRIM(value) LIKE '%SPIKE%' OR TRIM(value) LIKE '%FAIXA%' THEN 'HIDRAULICO'
        WHEN TRIM(value) LIKE '%ZERO%' THEN 'VERIFICAR'
        ELSE 'OUTRO'
    END AS CATEGORIA,
    
    -- Severidade
    CASE 
        WHEN TRIM(value) LIKE '%NEGATIVO%' OR TRIM(value) LIKE '%COMUNICACAO%' THEN 'CRITICO'
        WHEN TRIM(value) LIKE '%LIMITE%' OR TRIM(value) LIKE '%SPIKE%' OR TRIM(value) LIKE '%CONSTANTE%' THEN 'ALERTA'
        ELSE 'INFO'
    END AS SEVERIDADE

FROM [dbo].[MEDICAO_RESUMO_DIARIO]
CROSS APPLY STRING_SPLIT(DS_ANOMALIAS, ';')
WHERE DT_MEDICAO >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
  AND DS_ANOMALIAS IS NOT NULL
  AND TRIM(value) <> ''
GROUP BY TRIM(value);
GO

-- ============================================================================
-- VIEW 7: VW_EVOLUCAO_SCORE_DIARIO
-- Evolução do score de saúde por dia
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_EVOLUCAO_SCORE_DIARIO')
    DROP VIEW [dbo].[VW_EVOLUCAO_SCORE_DIARIO];
GO

CREATE VIEW [dbo].[VW_EVOLUCAO_SCORE_DIARIO]
AS
SELECT 
    DT_MEDICAO,
    COUNT(*) AS TOTAL_PONTOS,
    CAST(AVG(CAST(VL_SCORE_SAUDE AS DECIMAL(5,2))) AS DECIMAL(5,2)) AS SCORE_MEDIO,
    MIN(VL_SCORE_SAUDE) AS SCORE_MINIMO,
    MAX(VL_SCORE_SAUDE) AS SCORE_MAXIMO,
    
    SUM(CASE WHEN VL_SCORE_SAUDE >= 8 THEN 1 ELSE 0 END) AS QTD_SAUDAVEIS,
    SUM(CASE WHEN VL_SCORE_SAUDE BETWEEN 5 AND 7 THEN 1 ELSE 0 END) AS QTD_ALERTA,
    SUM(CASE WHEN VL_SCORE_SAUDE < 5 THEN 1 ELSE 0 END) AS QTD_CRITICOS,
    
    SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) AS TOTAL_ANOMALIAS,
    SUM(QTD_TRATAMENTOS) AS TOTAL_TRATAMENTOS,
    
    CAST(AVG(QTD_REGISTROS * 100.0 / 1440) AS DECIMAL(5,2)) AS COMPLETUDE_MEDIA

FROM [dbo].[MEDICAO_RESUMO_DIARIO]
WHERE DT_MEDICAO >= DATEADD(DAY, -30, CAST(GETDATE() AS DATE))
GROUP BY DT_MEDICAO;
GO

-- ============================================================================
-- VIEW 8: VW_HORAS_CRITICAS
-- Análise temporal de anomalias por hora do dia
-- ============================================================================

IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_HORAS_CRITICAS')
    DROP VIEW [dbo].[VW_HORAS_CRITICAS];
GO

CREATE VIEW [dbo].[VW_HORAS_CRITICAS]
AS
SELECT 
    NR_HORA,
    FORMAT(DATEADD(HOUR, NR_HORA, 0), 'HH:00') AS HORA_FORMATADA,
    
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT CD_PONTO_MEDICAO) AS TOTAL_PONTOS,
    
    -- Anomalias
    SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) AS TOTAL_ANOMALIAS,
    CAST(SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0) AS DECIMAL(5,2)) AS PERC_ANOMALIA,
    
    -- Por tipo
    SUM(CASE WHEN FL_VALOR_CONSTANTE = 1 THEN 1 ELSE 0 END) AS QTD_VALOR_CONSTANTE,
    SUM(CASE WHEN FL_VALOR_NEGATIVO = 1 THEN 1 ELSE 0 END) AS QTD_VALOR_NEGATIVO,
    SUM(CASE WHEN FL_FORA_FAIXA = 1 THEN 1 ELSE 0 END) AS QTD_FORA_FAIXA,
    SUM(CASE WHEN FL_SPIKE = 1 THEN 1 ELSE 0 END) AS QTD_SPIKES,
    SUM(CASE WHEN FL_ZEROS_SUSPEITOS = 1 THEN 1 ELSE 0 END) AS QTD_ZEROS,
    
    -- Estatísticas
    AVG(VL_MEDIA) AS MEDIA_GERAL,
    AVG(QTD_REGISTROS) AS REGISTROS_MEDIO,
    
    -- Classificação da hora
    CASE 
        WHEN CAST(SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0) AS DECIMAL(5,2)) > 20 THEN 'CRITICA'
        WHEN CAST(SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0) AS DECIMAL(5,2)) > 10 THEN 'ALERTA'
        ELSE 'NORMAL'
    END AS STATUS_HORA

FROM [dbo].[MEDICAO_RESUMO_HORARIO]
WHERE DT_HORA >= DATEADD(DAY, -7, CAST(GETDATE() AS DATE))
GROUP BY NR_HORA;
GO

-- ============================================================================
-- STORED PROCEDURE: SP_CONTEXTO_IA_COMPLETO
-- Gera contexto textual completo para análise por IA
-- ============================================================================

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_CONTEXTO_IA_COMPLETO]') AND type in (N'P'))
    DROP PROCEDURE [dbo].[SP_CONTEXTO_IA_COMPLETO];
GO

CREATE PROCEDURE [dbo].[SP_CONTEXTO_IA_COMPLETO]
    @DIAS_ANALISE INT = 7
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @DT_INICIO DATE = DATEADD(DAY, -@DIAS_ANALISE, CAST(GETDATE() AS DATE));
    DECLARE @CONTEXTO NVARCHAR(MAX) = '';
    
    -- Variáveis de resumo
    DECLARE @TOTAL_PONTOS INT, @SCORE_MEDIO DECIMAL(5,2), @PROBLEMAS_COMUNICACAO INT, 
            @PROBLEMAS_MEDIDOR INT, @PROBLEMAS_HIDRAULICO INT, @TOTAL_ANOMALIAS INT;
    
    SELECT 
        @TOTAL_PONTOS = COUNT(DISTINCT CD_PONTO_MEDICAO),
        @SCORE_MEDIO = AVG(CAST(VL_SCORE_SAUDE AS DECIMAL(5,2))),
        @PROBLEMAS_COMUNICACAO = SUM(CASE WHEN DS_TIPO_PROBLEMA = 'COMUNICACAO' THEN 1 ELSE 0 END),
        @PROBLEMAS_MEDIDOR = SUM(CASE WHEN DS_TIPO_PROBLEMA = 'MEDIDOR' THEN 1 ELSE 0 END),
        @PROBLEMAS_HIDRAULICO = SUM(CASE WHEN DS_TIPO_PROBLEMA = 'HIDRAULICO' THEN 1 ELSE 0 END),
        @TOTAL_ANOMALIAS = SUM(CASE WHEN FL_ANOMALIA = 1 THEN 1 ELSE 0 END)
    FROM [dbo].[MEDICAO_RESUMO_DIARIO]
    WHERE DT_MEDICAO >= @DT_INICIO;
    
    -- Montar contexto
    SET @CONTEXTO = '
=== CONTEXTO PARA ANÁLISE DE IA - SIMP ===
Período: Últimos ' + CAST(@DIAS_ANALISE AS VARCHAR) + ' dias

>>> RESUMO GERAL <<<
• Pontos monitorados: ' + CAST(@TOTAL_PONTOS AS VARCHAR) + '
• Score médio de saúde: ' + CAST(@SCORE_MEDIO AS VARCHAR) + '/10
• Total de anomalias: ' + CAST(@TOTAL_ANOMALIAS AS VARCHAR) + '

>>> CLASSIFICAÇÃO DOS PROBLEMAS <<<
• COMUNICAÇÃO (telemetria/rádio/bateria): ' + CAST(@PROBLEMAS_COMUNICACAO AS VARCHAR) + ' ocorrências
• MEDIDOR (sensor travado/defeito): ' + CAST(@PROBLEMAS_MEDIDOR AS VARCHAR) + ' ocorrências  
• HIDRÁULICO (valores fora faixa/spikes): ' + CAST(@PROBLEMAS_HIDRAULICO AS VARCHAR) + ' ocorrências

>>> PONTOS CRÍTICOS (Score < 5) <<<
';

    -- Adicionar pontos críticos
    SELECT @CONTEXTO = @CONTEXTO + 
        '• ' + ISNULL(PM.DS_NOME, 'Ponto ' + CAST(MRD.CD_PONTO_MEDICAO AS VARCHAR)) + 
        ' | Score: ' + CAST(MRD.VL_SCORE_SAUDE AS VARCHAR) + 
        ' | Problema: ' + ISNULL(MRD.DS_TIPO_PROBLEMA, 'N/A') +
        ' | ' + ISNULL(LEFT(MRD.DS_ANOMALIAS, 80), '') +
        CHAR(13) + CHAR(10)
    FROM [dbo].[MEDICAO_RESUMO_DIARIO] MRD
    LEFT JOIN [dbo].[PONTO_MEDICAO] PM ON MRD.CD_PONTO_MEDICAO = PM.CD_PONTO_MEDICAO
    WHERE MRD.DT_MEDICAO >= @DT_INICIO
      AND MRD.VL_SCORE_SAUDE < 5
    ORDER BY MRD.VL_SCORE_SAUDE ASC, MRD.DT_MEDICAO DESC;
    
    SET @CONTEXTO = @CONTEXTO + '
>>> TIPOS DE ANOMALIA MAIS FREQUENTES <<<
';

    SELECT @CONTEXTO = @CONTEXTO + 
        '• ' + TRIM(value) + ': ' + CAST(COUNT(*) AS VARCHAR) + ' ocorrências' + CHAR(13) + CHAR(10)
    FROM [dbo].[MEDICAO_RESUMO_DIARIO]
    CROSS APPLY STRING_SPLIT(DS_ANOMALIAS, ';')
    WHERE DT_MEDICAO >= @DT_INICIO
      AND DS_ANOMALIAS IS NOT NULL
      AND TRIM(value) <> ''
    GROUP BY TRIM(value)
    ORDER BY COUNT(*) DESC;
    
    SET @CONTEXTO = @CONTEXTO + '
>>> DIAGNÓSTICO AUTOMÁTICO <<<
';

    -- Adicionar diagnósticos
    IF @PROBLEMAS_COMUNICACAO > 0
        SET @CONTEXTO = @CONTEXTO + '⚠️ ' + CAST(@PROBLEMAS_COMUNICACAO AS VARCHAR) + ' pontos com problemas de COMUNICAÇÃO - verificar rádio, bateria e datalogger' + CHAR(13) + CHAR(10);
    
    IF @PROBLEMAS_MEDIDOR > 0
        SET @CONTEXTO = @CONTEXTO + '🔧 ' + CAST(@PROBLEMAS_MEDIDOR AS VARCHAR) + ' pontos com problemas de MEDIDOR - verificar sensor, conversor A/D' + CHAR(13) + CHAR(10);
    
    IF @PROBLEMAS_HIDRAULICO > 0
        SET @CONTEXTO = @CONTEXTO + '💧 ' + CAST(@PROBLEMAS_HIDRAULICO AS VARCHAR) + ' pontos com problemas HIDRÁULICOS - verificar escala, limites e configuração' + CHAR(13) + CHAR(10);
    
    SELECT @CONTEXTO AS CONTEXTO_IA;
END
GO

PRINT 'Views e procedures para dashboard criadas com sucesso!';
GO